future: true
permalink: /:title/
url: http://Sansanphus.github.io
name: Sansan
author: Sansan
qq: 704358474
email: sansantoday@163.com

duoshuo: Sansanphus
beian: 
cnzz: 
weibo: 
github: https://github.com/sansanphus
about: "哈喽哈喽嘿"

safe: true
paginate: 20
