future: true
permalink: /:title/
url: http://sansanphus.github.io
name: sansanphus
author: sansan
qq: 704358474@qq.com
email: sansantoday@qq.com

duoshuo: sansanphus
beian: 
cnzz: 
weibo: 
github: https://github.com/sansanphus
about: "这里是 sansanphus 的动感地带！"

safe: true
paginate: 20
